_layouts:
  - &layout-bbc-west
    [ 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 ]
  - &layout-bbc-east
    [ 16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31 ]
    #  - &layout-zdc-v-west
    #    [ ]
    #  - &layout-zdc-h-west
    #    [ ]
    #  - &layout-zdc-v-east
    #    [ ]
    #  - &layout-zdc-h-east
    #    [ ] 


_axes:
  - &centrality
    name: RecoEventExt/centrality
    bin-edges: [ 0, 5, 10, 20, 30,40,50,60,70,80]
  - &ax-tpcpt 
    name: TpcTracks/pT
    bin-edges: [ 0.2,0.4,0.6,0.8,1.0,1.2,1.4,1.6,1.8,2.0,2.2,2.4,2.6,2.8,3.2,3.6,4.0,4.4,4.8,5.2]
  - &ax-tpceta {name: TpcTracks/eta, nb: 10, lo: -1., hi: 1.}


_cuts:
STAR:
  event-variables:
    - RecoEventExt/centrality
  axes:
    - *centrality
  q-vectors:
    - name: protonE
      type: track
      phi: TpcTracks/phi
      weight: TpcTracks/pT
      norm: m
      harmonics: "11"
      corrections:
        - recentering
          #    - twist-and-rescale


      axes:
        - *ax-tpcpt
        - *ax-tpceta
      cuts:
        TpcTracks/charge: {equals: 1}
        TpcTracks/dca: {range: [-1,1] }
        TpcTracks/p: {range: [0.1,1000]}
        TpcTracks/nHits: { range: [15,50] }
        TpcTracks/nHits_Fit2Poss: {range: [0.52,2]}
        TpcTracks/nSigmaProton: { range: [-3,3]}
        TpcTracks/tofMass2: {range: [0.74,1.2]}
        TpcTracks/eta: {range: [ 0.05,1]}

    - name: protonW
      type: track
      phi: TpcTracks/phi
      weight: TpcTracks/pT
      norm: m
      harmonics: "11"
      corrections:
        - recentering
          #   - twist-and-rescale
      axes:
        - *ax-tpcpt
        - *ax-tpceta
      cuts:
        TpcTracks/charge: {equals: 1}
        TpcTracks/dca: {range: [-1,1] }
        TpcTracks/p: {range: [0.1,1000]}
        TpcTracks/nHits: { range: [15,50] }
        TpcTracks/nHits_Fit2Poss: {range: [0.52,2]}
        TpcTracks/nSigmaProton: { range: [-3,3]}
        TpcTracks/tofMass2: {range: [0.74,1.2]}
        TpcTracks/eta: {range: [ -1,-0.05]}

    - name: kaonE
      type: track
      phi: TpcTracks/phi
      weight: TpcTracks/pT
      norm: m
      harmonics: "11"
      corrections:
        - recentering
          #   - twist-and-rescale
      axes:
        - *ax-tpcpt
        - *ax-tpceta
      cuts:
        TpcTracks/charge: {equals: 1}
        TpcTracks/dca: {range: [-1,1] }
        TpcTracks/p: {range: [0.1,1000]}
        TpcTracks/nHits: { range: [15,50] }
        TpcTracks/nHits_Fit2Poss: {range: [0.52,2]}
        TpcTracks/nSigmaKaon: { range: [-3,3]}
        TpcTracks/tofMass2: {range: [0.2,0.32]}
        TpcTracks/eta: {range: [ 0.05,1]}

    - name: kaonW
      type: track
      phi: TpcTracks/phi
      weight: TpcTracks/pT
      norm: m
      harmonics: "11"
      corrections:
        - recentering
          #      - twist-and-rescale
      axes:
        - *ax-tpcpt
        - *ax-tpceta
      cuts:
        TpcTracks/charge: {equals: 1}
        TpcTracks/dca: {range: [-1,1] }
        TpcTracks/p: {range: [0.1,1000]}
        TpcTracks/nHits: { range: [15,50] }
        TpcTracks/nHits_Fit2Poss: {range: [0.52,2]}
        TpcTracks/nSigmaKaon: { range: [-3,3]}
        TpcTracks/tofMass2: {range: [0.2,0.32]}
        TpcTracks/eta: {range: [ -1,-0.05]}

    - name: pionE
      type: track
      phi: TpcTracks/phi
      weight: TpcTracks/pT
      norm: m
      harmonics: "11"
      corrections:
        - recentering
          #   - twist-and-rescale
      axes:
        - *ax-tpcpt
        - *ax-tpceta
      cuts:
        TpcTracks/charge: {equals: 1}
        TpcTracks/dca: {range: [-1,1] }
        TpcTracks/p: {range: [0.1,1000]}
        TpcTracks/nHits: { range: [15,50] }
        TpcTracks/nHits_Fit2Poss: {range: [0.52,2]}
        TpcTracks/nSigmaPion: { range: [-3,3]}
        TpcTracks/tofMass2: {range: [-0.15,0.1]}
        TpcTracks/eta: {range: [ 0.05,1]}

    - name: pionW
      type: track
      phi: TpcTracks/phi
      weight: TpcTracks/pT
      norm: m
      harmonics: "11"
      corrections:
        - recentering
          #     - twist-and-rescale
      axes:
        - *ax-tpcpt
        - *ax-tpceta
      cuts:
        TpcTracks/charge: {equals: 1}
        TpcTracks/dca: {range: [-1,1] }
        TpcTracks/p: {range: [0.1,1000]}
        TpcTracks/nHits: { range: [15,50] }
        TpcTracks/nHits_Fit2Poss: {range: [0.52,2]}
        TpcTracks/nSigmaPion: { range: [-3,3]}
        TpcTracks/tofMass2: {range: [-0.15,0.1]}
        TpcTracks/eta: {range: [ -1,-0.05]}

    - name: hadronsE
      type: track
      phi: TpcTracks/phi
      weight: TpcTracks/pT
      norm: m
      harmonics: "11"
      corrections:
        - recentering
          #   - twist-and-rescale
      cuts:
        TpcTracks/dca: {range: [-1,1] }
        TpcTracks/p: {range: [0.1,1000]}
        TpcTracks/nHitsFit: { range: [15,50] }
        TpcTracks/nHits_Fit2Poss: {range: [0.52,2]}
        TpcTracks/eta: {range: [ 0.05,1]}

    - name: hadronsW
      type: track
      phi: TpcTracks/phi
      weight: TpcTracks/pT
      norm: m
      harmonics: "11"
      corrections:
        - recentering
          #    - twist-and-rescale
      cuts:
        TpcTracks/dca: {range: [-1,1] }
        TpcTracks/p: {range: [0.1,1000]}
        TpcTracks/nHitsFit: { range: [15,50] }
        TpcTracks/nHits_Fit2Poss: {range: [0.52,2]}
        TpcTracks/eta: {range: [ -1,-0.05]}

          
    - name: hadronsEv
      type: track
      phi: TpcTracks/phi
      weight: TpcTracks/pT
      norm: m
      harmonics: "11"
      corrections:
        - recentering
          #   - twist-and-rescale
      axes:
        - *ax-tpcpt
        - *ax-tpceta
      cuts:
        TpcTracks/dca: {range: [-1,1] }
        TpcTracks/p: {range: [0.1,1000]}
        TpcTracks/nHitsFit: { range: [15,50] }
        TpcTracks/nHits_Fit2Poss: {range: [0.52,2]}
        TpcTracks/eta: {range: [ 0.05,1]}

    - name: hadronsWv
      type: track
      phi: TpcTracks/phi
      weight: TpcTracks/pT
      norm: m
      harmonics: "11"
      corrections:
        - recentering
          #     - twist-and-rescale
      axes:
        - *ax-tpcpt
        - *ax-tpceta
      cuts:
        TpcTracks/dca: {range: [-1,1] }
        TpcTracks/p: {range: [0.1,1000]}
        TpcTracks/nHitsFit: { range: [15,50] }
        TpcTracks/nHits_Fit2Poss: {range: [0.52,2]}
        TpcTracks/eta: {range: [ -1,-0.05]}


       #Reference Detector

    - name: bbcEast
      type: channel
      phi: BbcModules/phi
      weight: BbcModules/signal
      harmonics: "11"
      norm: m
      corrections:
        - recentering
          #   - twist-and-rescale
      channel-ids: *layout-bbc-east
    - name: bbcWest
      type: channel
      phi: BbcModules/phi
      weight: BbcModules/signal
      harmonics: "11"
      norm: m
      corrections:
        - recentering
          #   - twist-and-rescale
      channel-ids: *layout-bbc-west
        #    - name: ZdcVerticalEast
        #      type: channel
        #      phi: ZdcHitsVertical/phi
        #      weight: ZdcHitsVertical/signal
        #      harmonics: "11"
        #      norm: m
        #      corrections:
        #        - recentering
        #        - twist-and-rescale
        #      channel-ids: *layout-zdc-v-east
        #    - name: ZdcVerticalWest
        #      type: channel
        #      phi: ZdcHitsVertical/phi
        #      weight: ZdcHitsVertical/signal
        #      harmonics: "11"
        #      norm: m
        #      corrections:
        #        - recentering
        #        - twist-and-rescale
          #      channel-ids: *layout-zdc-v-west
        #    - name: ZdcHorizontalEast
      #      type: channel
        #      phi: ZdcHitsHorizontal/phi
        #      weight: ZdcHitsHorizontal/signal
        #      harmonics: "11"
        #      norm: m
        #      corrections:
        #        - recentering
          #        - twist-and-rescale
          #      channel-ids: *layout-zdc-h-east
        #    - name: ZdcHorizontalWest
      #      type: channel
        #      phi: ZdcHitsHorizontal/phi
        #      weight: ZdcHitsHorizontal/signal
        #      harmonics: "11"
        #      norm: m
        #      corrections:
        #        - recentering
          #        - twist-and-rescale
#      channel-ids: *layout-zdc-h-west

